import json
import pulumi
import pulumi_aws as aws
from typing import Optional, TypedDict, List


class S3BucketArgs(TypedDict):

    environment: pulumi.Input[str]
    """Value for the Environment tag and Pulumi resource name prefix."""

    cors_allowed_origins: Optional[pulumi.Input[List[str]]]
    """List of allowed CORS origins. Default: ['*']"""

    versioning_enabled: Optional[pulumi.Input[bool]]
    """Whether to enable bucket versioning. Default: True"""

    sse_algorithm: Optional[pulumi.Input[str]]
    """SSE algorithm — 'AES256' or 'aws:kms'. Default: AES256"""

    kms_master_key_id: Optional[pulumi.Input[str]]
    """KMS key ARN/ID; only used when sse_algorithm='aws:kms'."""



class S3Bucket(pulumi.ComponentResource):
    """
    Creates an S3 bucket together with all companion resources:
    versioning, encryption, public-access blocking, ownership controls,
    CORS, lifecycle rules, access logging, SNS event notifications,
    and a security bucket policy.

    Bucket names are auto-generated by Pulumi/AWS. The Pulumi resource
    name (and all child resource names) are derived from the environment arg.

    Child resource names intentionally mirror the naming used in the
    standalone __main__.py resources so that aliases can be used to
    adopt those existing resources without recreation when replacing the
    inline resources with this component.
    """

    bucket_id: pulumi.Output[str]
    """ID (name) of the main S3 bucket."""

    bucket_arn: pulumi.Output[str]
    """ARN of the main S3 bucket."""

    bucket_domain_name: pulumi.Output[str]
    """Domain name of the main S3 bucket."""

    bucket_regional_domain_name: pulumi.Output[str]
    """Regional domain name of the main S3 bucket."""

    log_bucket_id: pulumi.Output[str]
    """ID (name) of the access-log S3 bucket."""

    log_bucket_arn: pulumi.Output[str]
    """ARN of the access-log S3 bucket."""

    notification_topic_arn: pulumi.Output[str]
    """ARN of the SNS topic receiving bucket event notifications."""

    def __init__(
        self,
        name: str,
        args: S3BucketArgs,
        opts: Optional[pulumi.ResourceOptions] = None,
    ):
        super().__init__("s3bucket:index:S3Bucket", name, {}, opts)

        environment = args["environment"]
        cors_allowed_origins = args.get("cors_allowed_origins") or ["*"]
        versioning_enabled = args.get("versioning_enabled")
        if versioning_enabled is None:
            versioning_enabled = True
        sse_algorithm = args.get("sse_algorithm") or "AES256"
        kms_master_key_id = args.get("kms_master_key_id")


        # -------------------------------------------------------------------
        # Logging bucket
        # -------------------------------------------------------------------
        log_bucket = aws.s3.BucketV2(
            f"{name}-log-bucket",
            force_destroy=True,  # Required to allow the log bucket to be deleted without manual cleanup of logs
            tags={
                "Environment": environment,
                "Purpose": "s3-access-logs",
            },
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        log_bucket_ownership_controls = aws.s3.BucketOwnershipControls(
            f"{name}-log-bucket-ownership-controls",
            bucket=log_bucket.id,
            rule=aws.s3.BucketOwnershipControlsRuleArgs(
                object_ownership="BucketOwnerPreferred",
            ),
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        log_bucket_public_access_block = aws.s3.BucketPublicAccessBlock(
            f"{name}-log-bucket-public-access-block",
            bucket=log_bucket.id,
            block_public_acls=True,
            block_public_policy=True,
            ignore_public_acls=True,
            restrict_public_buckets=True,
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        log_bucket_acl = aws.s3.BucketAclV2(
            f"{name}-log-bucket-acl",
            bucket=log_bucket.id,
            acl="log-delivery-write",
            opts=pulumi.ResourceOptions(
                parent=self,
                depends_on=[log_bucket_ownership_controls, log_bucket_public_access_block],
            ),
        )

        # -------------------------------------------------------------------
        # Main bucket
        # -------------------------------------------------------------------
        bucket = aws.s3.BucketV2(
            f"{name}-bucket",
            tags={
                "Environment": environment,
            },
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        # Versioning
        bucket_versioning = aws.s3.BucketVersioningV2(
            f"{name}-bucket-versioning",
            bucket=bucket.id,
            versioning_configuration=aws.s3.BucketVersioningV2VersioningConfigurationArgs(
                status="Enabled" if versioning_enabled else "Suspended",
            ),
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        # Server-side encryption
        aws.s3.BucketServerSideEncryptionConfigurationV2(
            f"{name}-bucket-encryption",
            bucket=bucket.id,
            rules=[
                aws.s3.BucketServerSideEncryptionConfigurationV2RuleArgs(
                    apply_server_side_encryption_by_default=aws.s3.BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs(
                        sse_algorithm=sse_algorithm,
                        kms_master_key_id=kms_master_key_id,
                    ),
                    bucket_key_enabled=(sse_algorithm == "aws:kms"),
                )
            ],
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        # Public access block
        bucket_pab = aws.s3.BucketPublicAccessBlock(
            f"{name}-bucket-public-access-block",
            bucket=bucket.id,
            block_public_acls=True,
            block_public_policy=True,
            ignore_public_acls=True,
            restrict_public_buckets=True,
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        # Ownership controls
        bucket_ownership = aws.s3.BucketOwnershipControls(
            f"{name}-bucket-ownership-controls",
            bucket=bucket.id,
            rule=aws.s3.BucketOwnershipControlsRuleArgs(
                object_ownership="BucketOwnerEnforced",
            ),
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        # CORS
        aws.s3.BucketCorsConfigurationV2(
            f"{name}-bucket-cors",
            bucket=bucket.id,
            cors_rules=[
                aws.s3.BucketCorsConfigurationV2CorsRuleArgs(
                    allowed_headers=["*"],
                    allowed_methods=["GET", "HEAD", "PUT", "POST", "DELETE"],
                    allowed_origins=cors_allowed_origins,
                    expose_headers=["ETag"],
                    max_age_seconds=3600,
                )
            ],
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        # Lifecycle
        aws.s3.BucketLifecycleConfigurationV2(
            f"{name}-bucket-lifecycle",
            bucket=bucket.id,
            rules=[
                aws.s3.BucketLifecycleConfigurationV2RuleArgs(
                    id="transition-current-objects",
                    status="Enabled",
                    transitions=[
                        aws.s3.BucketLifecycleConfigurationV2RuleTransitionArgs(
                            days=30, storage_class="STANDARD_IA",
                        ),
                        aws.s3.BucketLifecycleConfigurationV2RuleTransitionArgs(
                            days=90, storage_class="GLACIER",
                        ),
                        aws.s3.BucketLifecycleConfigurationV2RuleTransitionArgs(
                            days=365, storage_class="DEEP_ARCHIVE",
                        ),
                    ],
                ),
                aws.s3.BucketLifecycleConfigurationV2RuleArgs(
                    id="expire-noncurrent-versions",
                    status="Enabled",
                    noncurrent_version_transitions=[
                        aws.s3.BucketLifecycleConfigurationV2RuleNoncurrentVersionTransitionArgs(
                            noncurrent_days=30, storage_class="STANDARD_IA",
                        ),
                    ],
                    noncurrent_version_expiration=aws.s3.BucketLifecycleConfigurationV2RuleNoncurrentVersionExpirationArgs(
                        noncurrent_days=90,
                    ),
                ),
                aws.s3.BucketLifecycleConfigurationV2RuleArgs(
                    id="abort-incomplete-multipart-uploads",
                    status="Enabled",
                    abort_incomplete_multipart_upload=aws.s3.BucketLifecycleConfigurationV2RuleAbortIncompleteMultipartUploadArgs(
                        days_after_initiation=7,
                    ),
                ),
            ],
            opts=pulumi.ResourceOptions(
                parent=self,
                depends_on=[bucket_versioning],
            ),
        )

        # Access logging
        aws.s3.BucketLoggingV2(
            f"{name}-bucket-logging",
            bucket=bucket.id,
            target_bucket=log_bucket.id,
            target_prefix="s3-access-logs/",
            opts=pulumi.ResourceOptions(
                parent=self,
                depends_on=[log_bucket_acl],
            ),
        )

        # SNS notification topic
        notification_topic = aws.sns.Topic(
            f"{name}-bucket-notification-topic",
            tags={"Environment": environment},
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        aws.sns.TopicPolicy(
            f"{name}-bucket-notification-topic-policy",
            arn=notification_topic.arn,
            policy=pulumi.Output.all(notification_topic.arn, bucket.arn).apply(
                lambda a: json.dumps(
                    {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Principal": {"Service": "s3.amazonaws.com"},
                                "Action": "SNS:Publish",
                                "Resource": a[0],
                                "Condition": {"ArnLike": {"aws:SourceArn": a[1]}},
                            }
                        ],
                    }
                )
            ),
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        aws.s3.BucketNotification(
            f"{name}-bucket-notification",
            bucket=bucket.id,
            topics=[
                aws.s3.BucketNotificationTopicArgs(
                    topic_arn=notification_topic.arn,
                    events=["s3:ObjectCreated:*", "s3:ObjectRemoved:*"],
                )
            ],
            opts=pulumi.ResourceOptions(
                parent=self,
                depends_on=[notification_topic],
            ),
        )

        # Bucket policy
        aws.s3.BucketPolicy(
            f"{name}-bucket-policy",
            bucket=bucket.id,
            policy=bucket.arn.apply(
                lambda arn: json.dumps(
                    {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Sid": "DenyNonHTTPS",
                                "Effect": "Deny",
                                "Principal": "*",
                                "Action": "s3:*",
                                "Resource": [arn, f"{arn}/*"],
                                "Condition": {"Bool": {"aws:SecureTransport": "false"}},
                            },
                            {
                                "Sid": "DenyOldTLS",
                                "Effect": "Deny",
                                "Principal": "*",
                                "Action": "s3:*",
                                "Resource": [arn, f"{arn}/*"],
                                "Condition": {"NumericLessThan": {"s3:TlsVersion": "1.2"}},
                            },
                        ],
                    }
                )
            ),
            opts=pulumi.ResourceOptions(
                parent=self,
                depends_on=[bucket_pab, bucket_ownership],
            ),
        )

        self.bucket_id = bucket.id
        self.bucket_arn = bucket.arn
        self.bucket_domain_name = bucket.bucket_domain_name
        self.bucket_regional_domain_name = bucket.bucket_regional_domain_name
        self.log_bucket_id = log_bucket.id
        self.log_bucket_arn = log_bucket.arn
        self.notification_topic_arn = notification_topic.arn

        self.register_outputs({})
